name: Generate contribution snake

on:
  schedule:
    # Her 12 saatte bir UTC ile 00:00, 12:00'de çalışır
    - cron: '0 0,12 * * *' 
  workflow_dispatch:
  
permissions:
  # 'output' branch'ine push yapmak için gerekli
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Platane/snk Action'ını kullan
      - name: Generate SVG (snake)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mustafayzc 
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Generate SVG (snake)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mustafayzc # Kullanıcı adınız
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
        
        env:
          # Bu, Action'a özel katkı verilerini okuma yetkisi verir.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
